version: 2.1

orbs:
  # The node orb contains a set or prepackaged circleci configuration you can use
  # Orbs help you with common scripting around a language/tool so you dont have to copy
  # and paste it everywhere.
  node: circleci/node@4.1

workflows:
  sample:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    executor: cimg/node:15.1
    # Checkout the code as the first step.
    # The node orb's install-packages step will install the dependencies from a package.json
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test

