version: 2.1

orbs:
  # The node orb contains a set or prepackaged circleci configuration you can use
  # Orbs help you with common scripting around a language/tool so you dont have to copy
  # and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

workflows:
  sample:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run. 
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows 
    jobs:
      - build-and-test

jobs:
  build-and-test:  # This is the name of the job, feel free to change it to better match what you're trying to do!
    # These next lines defines a docker executors: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from dockerhub or use one of the convenience images from CircleCI's Developer Hub
    # A list of available CircleCI docker convenience images are available here: https://circleci.com/developer/images/image/cimg/node
    # The executor is the environment in which the steps below will be executed
    docker:
      - image: cimg/node:15.1
    # Checkout the code as the first step. This is a dedicated CircleCI step.
    # Next, the node orb's install-packages step will install the dependencies from a package.json
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      - checkout
      - node/install-packages
      # - run: npm install  # If your project is having issues using the orb, remove the line above and uncomment this!
      - run:
          name: Run tests
          command: npm test

